// 移动端图标集选择配置（模块内路径版）
module.exports = {
    // 选入模式（正则字符串，基于“文件名不含 .svg 的部分”匹配）
    includePatterns: [
        '^(arrow|chevron|caret).*',
        '^(box-arrow).*',
        '^(plus|dash|x|check)(|-.+)$',
        '^(three-dots|three-dots-vertical).*',
        '^(list|filter|funnel|sliders?|toggles?).*',
        '^(grid|columns|layout|app|apps?).*',
        '^(search).*',
        '^(house).*',
        '^(gear|wrench|tools|nut).*',
        '^(bell|alarm|hourglass|stopwatch|timer|clock).*',
        '^(chat|envelope|inbox|send|mailbox).*',
        '^(telephone|phone|reception).*',
        '^(camera|camera-video|image|images|film|play|pause|stop|skip|record|mic|volume|music-note|speaker).*',
        '^(download|upload|cloud).*',
        '^(heart|star|hand-thumbs).*',
        '^(geo|pin|pin-map|map|compass|signpost).*',
        '^(calendar|date|time).*',
        '^(cart|bag|wallet|credit-card|cash|coin|currency|tag|tags|barcode|qr-code|receipt).*',
        '^(file|file-earmark|folder).*',
        '^(bookmark|bookmarks|book|journal).*',
        '^(trash).*',
        '^(pencil|pen|eraser|scissors|clipboard|paperclip|undo|redo).*',
        '^(eye).*',
        '^(info|exclamation|question).*',
        '^(shield|lock|unlock|key|safe).*',
        '^(wifi|bluetooth|battery|lightning|sun|moon|brightness|display|phone|tablet).*',
        '^(arrow-(clockwise|counterclockwise)|arrow-repeat|bootstrap-reboot|repeat).*',
        '^(gift|door|house-door|box|box-seam).*',
    ],
    // 显式补充
    explicitInclude: [
        'chevron-left','chevron-right','chevron-up','chevron-down',
        'arrow-left','arrow-right','arrow-up','arrow-down',
        'arrow-left-short','arrow-right-short','arrow-up-short','arrow-down-short',
        'caret-left','caret-right','caret-up','caret-down',
        'plus-circle','plus-circle-fill','dash-circle','dash-circle-fill',
        'x-circle','x-circle-fill','check-circle','check-circle-fill',
        'plus-square','plus-square-fill','dash-square','dash-square-fill',
        'x-square','x-square-fill','check-square','check-square-fill',
        'check-lg','x-lg','plus-lg','dash-lg',
        'three-dots','three-dots-vertical','list','list-ul','list-ol','list-check','filter','funnel',
        'sliders','sliders2','sliders2-vertical',
        'house','house-fill','house-door','house-door-fill','app','app-indicator',
        'grid','grid-fill','grid-3x3-gap','grid-3x3-gap-fill',
        'search',
        'play','play-fill','play-circle','play-circle-fill',
        'pause','pause-fill','pause-circle','pause-circle-fill',
        'stop','stop-fill','stop-circle','stop-circle-fill',
        'skip-start','skip-start-fill','skip-start-circle','skip-start-circle-fill',
        'skip-end','skip-end-fill','skip-end-circle','skip-end-circle-fill',
        'fast-forward','fast-forward-fill','rewind','rewind-fill',
        'chat','chat-fill','chat-dots','chat-dots-fill',
        'chat-left','chat-left-fill','chat-left-dots','chat-left-dots-fill',
        'chat-right','chat-right-fill','chat-right-dots','chat-right-dots-fill',
        'envelope','envelope-fill','envelope-open','envelope-open-fill','send','send-fill','inbox','inbox-fill',
        'telephone','telephone-fill','telephone-inbound','telephone-outbound',
        'heart','heart-fill','heart-half','star','star-fill','star-half',
        'alarm','alarm-fill','clock','clock-fill','stopwatch','stopwatch-fill','hourglass','hourglass-split',
        'cart','cart-fill','bag','bag-fill','bag-check','bag-plus',
        'wallet','wallet-fill','credit-card','credit-card-2-back','credit-card-2-front',
        'cash','cash-stack','cash-coin','coin',
        'currency-dollar','currency-yen','currency-euro','currency-pound','currency-bitcoin',
        'tag','tag-fill','tags','tags-fill','barcode','qr-code','qr-code-scan','receipt','receipt-cutoff',
        'geo','geo-alt','geo-alt-fill','pin','pin-fill','pin-map','pin-map-fill','map','compass',
        'file','file-text','file-earmark','file-earmark-text','file-earmark-pdf','file-earmark-image','file-earmark-zip',
        'folder','folder2','folder-fill','folder-plus','folder-minus','folder-check',
        'bookmark','bookmark-fill','bookmarks','bookmarks-fill','book','book-fill','journal','journal-text',
        'pencil','pencil-fill','pencil-square','pen','pen-fill','eraser','scissors',
        'clipboard','clipboard-check','clipboard-data','paperclip','trash','trash-fill','trash2','trash2-fill',
        'info-circle','info-circle-fill',
        'exclamation-triangle','exclamation-triangle-fill',
        'exclamation-circle','exclamation-circle-fill',
        'question-circle','question-circle-fill',
        'shield','shield-fill','shield-check','shield-lock','shield-exclamation',
        'lock','unlock','key','safe',
        'eye','eye-fill','eye-slash','eye-slash-fill',
        'wifi','wifi-off','bluetooth','battery','battery-half','battery-full','battery-charging',
        'lightning','lightning-charge','sun','sun-fill','moon','moon-fill','brightness-high','brightness-low',
        'display','phone','tablet',
        'arrow-clockwise','arrow-counterclockwise','arrow-repeat','bootstrap-reboot',
        'gift','gift-fill','door-closed','door-open','box','box-seam',
    ],
    // 排除模式：文件类型/品牌/emoji 等
    excludePatterns: [
        '^filetype-.*',
        '^(google|apple|microsoft|facebook|twitter|instagram|tiktok|youtube|weibo|alipay|wechat|qq|baidu|bilibili|reddit|linkedin|paypal|amazon|dribbble|figma|behance|slack|discord|medium|tencent|bootstrap)$',
        '^emoji-.*',
    ],
    // 输出目录与锁文件（相对 lucky-ui 模块根）
    outDir: 'assets/bootstrap-icons-selected',
    lockFile: 'scripts/iconset.mobile.lock.json',
};