export interface ShowcaseCase {
  slug: string;
  title: string;
  group: 'basic' | 'form' | 'feedback' | 'advanced';
  verifyStatus: 'verified' | 'pending';
  riskLevel: 'low' | 'medium' | 'high';
  visualEnabled: boolean;
  riskNotes: string[];
}

/**
 * Showcase 组件清单。
 * 注意事项：仅放可稳定回归的组件，避免动画组件引入噪音截图。
 */
export const SHOWCASE_CASES: ShowcaseCase[] = [
  {
    slug: 'button',
    title: 'Button 按钮',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['点击态在小程序按压反馈与 H5 不一致。'],
  },
  {
    slug: 'action-sheet',
    title: 'ActionSheet 动作面板',
    group: 'feedback',
    verifyStatus: 'pending',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['浮层动画与安全区需按 H5/App/小程序分别复核。'],
  },
  {
    slug: 'badge',
    title: 'Badge 徽标',
    group: 'basic',
    verifyStatus: 'pending',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需要重点覆盖数字、红点、文字徽标的尺寸稳定性。'],
  },
  {
    slug: 'cell',
    title: 'Cell 单元格',
    group: 'basic',
    verifyStatus: 'pending',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['长文本、省略号、右侧插槽对齐需要持续回归。'],
  },
  {
    slug: 'checkbox',
    title: 'Checkbox 复选框',
    group: 'form',
    verifyStatus: 'pending',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需覆盖选中、禁用、半选和分组联动。'],
  },
  {
    slug: 'collapse',
    title: 'Collapse 折叠面板',
    group: 'basic',
    verifyStatus: 'pending',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['展开动画与内容高度在低端设备需复核。'],
  },
  {
    slug: 'form',
    title: 'Form 表单',
    group: 'form',
    verifyStatus: 'pending',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['校验链路依赖交互断言，视觉截图只能作为辅助。'],
  },
  {
    slug: 'image',
    title: 'Image 图片',
    group: 'advanced',
    verifyStatus: 'pending',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['加载失败、懒加载和裁剪模式依赖网络与平台表现。'],
  },
  {
    slug: 'input',
    title: 'Input 输入框',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['不同平台 placeholder 渲染基线存在细微差异。'],
  },
  {
    slug: 'notice-bar',
    title: 'NoticeBar 通知栏',
    group: 'basic',
    verifyStatus: 'pending',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['滚动公告存在时间轴噪音，需以交互或定格状态验证。'],
  },
  {
    slug: 'progress',
    title: 'Progress 进度条',
    group: 'advanced',
    verifyStatus: 'pending',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需覆盖线形、圆形、不同百分比与状态色。'],
  },
  {
    slug: 'radio',
    title: 'Radio 单选框',
    group: 'form',
    verifyStatus: 'pending',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需覆盖选中、禁用和分组互斥。'],
  },
  {
    slug: 'rate',
    title: 'Rate 评分',
    group: 'form',
    verifyStatus: 'pending',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需覆盖只读、清空、半星和尺寸变化。'],
  },
  {
    slug: 'segmented',
    title: 'Segmented 分段器',
    group: 'basic',
    verifyStatus: 'pending',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['长文案与激活滑块对齐需要持续回归。'],
  },
  {
    slug: 'slider',
    title: 'Slider 滑块',
    group: 'form',
    verifyStatus: 'pending',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['拖拽手势、范围模式与刻度显示需要交互验证。'],
  },
  {
    slug: 'stepper',
    title: 'Stepper 步进器',
    group: 'form',
    verifyStatus: 'pending',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需覆盖最小值、最大值、禁用与精度。'],
  },
  {
    slug: 'picker',
    title: 'Picker 选择器',
    group: 'form',
    verifyStatus: 'pending',
    riskLevel: 'high',
    visualEnabled: true,
    riskNotes: ['⚠️可能存在平台差异：各端选择器 UI 与交互能力不同。'],
  },
  {
    slug: 'tabs',
    title: 'Tabs 标签页',
    group: 'basic',
    verifyStatus: 'pending',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['滚动与下划线动画在低端机型可能出现抖动。'],
  },
  {
    slug: 'tooltip',
    title: 'Tooltip 文字提示',
    group: 'feedback',
    verifyStatus: 'pending',
    riskLevel: 'high',
    visualEnabled: true,
    riskNotes: ['⚠️可能存在平台差异：定位与层级在 App/WebView 需重点验证。'],
  },
  {
    slug: 'waterfall',
    title: 'Waterfall 瀑布流',
    group: 'advanced',
    verifyStatus: 'pending',
    riskLevel: 'high',
    visualEnabled: true,
    riskNotes: ['⚠️可能存在平台差异：图片加载节奏会影响列高计算。'],
  },
  {
    slug: 'meta-row',
    title: 'MetaRow 结构行',
    group: 'basic',
    verifyStatus: 'pending',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['用于信息行布局，建议重点验证长文本省略与金额对齐。'],
  },
];
