export interface ShowcaseCase {
  slug: string;
  title: string;
  group: 'basic' | 'form' | 'feedback' | 'advanced';
  verifyStatus: 'verified' | 'pending';
  riskLevel: 'low' | 'medium' | 'high';
  visualEnabled: boolean;
  riskNotes: string[];
}

/**
 * Showcase 组件清单。
 * 注意事项：仅放可稳定回归的组件，避免动画组件引入噪音截图。
 */
export const SHOWCASE_CASES: ShowcaseCase[] = [
  {
    slug: 'button',
    title: 'Button 按钮',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['点击态在小程序按压反馈与 H5 不一致。'],
  },
  {
    slug: 'calendar',
    title: 'Calendar 日历',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['日期范围、多选和滚动定位需覆盖不同平台尺寸与 webkit 渲染差异。'],
  },
  {
    slug: 'card',
    title: 'Card 卡片',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['标题、封面、操作区和 hover 态需要保持布局稳定。'],
  },
  {
    slug: 'icon',
    title: 'Icon 图标',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['字体资源路径与渲染平滑度需在 App/WebView 复核。'],
  },
  {
    slug: 'avatar',
    title: 'Avatar 头像',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['图片加载失败时需覆盖 fallback 图标与文字。'],
  },
  {
    slug: 'backtop',
    title: 'Backtop 回到顶部',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['fixed 定位、页面滚动与容器受控滚动需按 H5/App/小程序分别复核。'],
  },
  {
    slug: 'action-sheet',
    title: 'ActionSheet 动作面板',
    group: 'feedback',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['浮层动画与安全区需按 H5/App/小程序分别复核。'],
  },
  {
    slug: 'badge',
    title: 'Badge 徽标',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需要重点覆盖数字、红点、文字徽标的尺寸稳定性。'],
  },
  {
    slug: 'cell',
    title: 'Cell 单元格',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['长文本、省略号、右侧插槽对齐需要持续回归。'],
  },
  {
    slug: 'carousel',
    title: 'Carousel 轮播',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['自动播放、竖向轮播和卡片模式需关注低端 WebView 动画稳定性。'],
  },
  {
    slug: 'divider',
    title: 'Divider 分割线',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['垂直分割线需覆盖行内高度与居中对齐。'],
  },
  {
    slug: 'empty',
    title: 'Empty 空状态',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['内置 SVG 通过 image 渲染，需确认小程序端 data URI 可见。'],
  },
  {
    slug: 'checkbox',
    title: 'Checkbox 复选框',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需覆盖选中、禁用、半选和分组联动。'],
  },
  {
    slug: 'collapse',
    title: 'Collapse 折叠面板',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['展开动画与内容高度在低端设备需复核。'],
  },
  {
    slug: 'curtain',
    title: 'Curtain 幕帘',
    group: 'feedback',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['fixed 浮层、外链跳转与遮罩关闭需按 H5/App/小程序分别复核。'],
  },
  {
    slug: 'countdown',
    title: 'Countdown 倒计时',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['倒计时存在时间轴噪音，视觉回归需定格或以交互断言补充。'],
  },
  {
    slug: 'date-picker',
    title: 'DatePicker 日期选择',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['弹层、日历面板与滚轮模式组合复杂，需以交互断言补充截图验证。'],
  },
  {
    slug: 'dropdown',
    title: 'Dropdown 下拉菜单',
    group: 'feedback',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['fixed 定位、点击外部关闭与菜单层级需按 H5/App/小程序复核。'],
  },
  {
    slug: 'form',
    title: 'Form 表单',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['校验链路依赖交互断言，视觉截图只能作为辅助。'],
  },
  {
    slug: 'modal',
    title: 'Modal 模态框',
    group: 'feedback',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['遮罩、异步确认与弹出动画需要交互断言，截图只作辅助。'],
  },
  {
    slug: 'image',
    title: 'Image 图片',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['加载失败、懒加载和裁剪模式依赖网络与平台表现。'],
  },
  {
    slug: 'horizontal-scroll',
    title: 'HorizontalScroll 横向滚动',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['横向滚动条隐藏依赖 webkit，子项宽度需由业务明确约束。'],
  },
  {
    slug: 'grid',
    title: 'Grid 宫格',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['分页宫格、图标尺寸和长文本换行需要持续视觉回归。'],
  },
  {
    slug: 'chart-lite',
    title: 'ChartLite 轻量图表',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: [
      '聚合覆盖 area/ring/sparkline/stat-card/radar-lite，触摸点位与 webkit 渲染需平台复核。',
    ],
  },
  {
    slug: 'chart-bar',
    title: 'ChartBar 柱状图',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['Canvas 尺寸、柱宽和坐标轴文字需在高低密度屏持续回归。'],
  },
  {
    slug: 'chart-line',
    title: 'ChartLine 折线图',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['Canvas 折线、面积填充和点位标记需保持缩放稳定。'],
  },
  {
    slug: 'chart-pie',
    title: 'ChartPie 饼图',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['扇区角度、环形宽度和图例排版需持续视觉回归。'],
  },
  {
    slug: 'choice',
    title: 'Choice 快选',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['单选、多选、禁用和长文本选项需要持续回归。'],
  },
  {
    slug: 'anchor',
    title: 'Anchor 锚点',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['滚动定位依赖节点查询，嵌套滚动容器需按平台复核。'],
  },
  {
    slug: 'index-bar',
    title: 'IndexBar 索引栏',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['fixed 索引浮层和触摸滑动需按小程序与 H5 分别复核。'],
  },
  {
    slug: 'input',
    title: 'Input 输入框',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['不同平台 placeholder 渲染基线存在细微差异。'],
  },
  {
    slug: 'loading',
    title: 'Loading 加载',
    group: 'feedback',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['动画帧与 webkit 渲染在低端 WebView 可能存在差异。'],
  },
  {
    slug: 'navbar',
    title: 'Navbar 导航栏',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['fixed 顶部定位、安全区和透明态需要按目标端人工复核。'],
  },
  {
    slug: 'notice-bar',
    title: 'NoticeBar 通知栏',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['滚动公告存在时间轴噪音，需以交互或定格状态验证。'],
  },
  {
    slug: 'progress',
    title: 'Progress 进度条',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需覆盖线形、圆形、不同百分比与状态色。'],
  },
  {
    slug: 'pull-refresh',
    title: 'PullRefresh 下拉刷新',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['原生下拉触发依赖 scroll-view 与页面配置，需按 H5/小程序分别回归。'],
  },
  {
    slug: 'radio',
    title: 'Radio 单选框',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需覆盖选中、禁用和分组互斥。'],
  },
  {
    slug: 'rate',
    title: 'Rate 评分',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需覆盖只读、清空、半星和尺寸变化。'],
  },
  {
    slug: 'segmented',
    title: 'Segmented 分段器',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['长文案与激活滑块对齐需要持续回归。'],
  },
  {
    slug: 'skeleton',
    title: 'Skeleton 骨架屏',
    group: 'feedback',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['行数、头像和动画占位需要保持布局稳定。'],
  },
  {
    slug: 'space',
    title: 'Space 间距',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['横向、纵向、换行与 fill 布局需要持续视觉回归。'],
  },
  {
    slug: 'tag',
    title: 'Tag 标签',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['关闭态与禁用态需保持点击事件边界清晰。'],
  },
  {
    slug: 'slider',
    title: 'Slider 滑块',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['拖拽手势、范围模式与刻度显示需要交互验证。'],
  },
  {
    slug: 'stepper',
    title: 'Stepper 步进器',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['需覆盖最小值、最大值、禁用与精度。'],
  },
  {
    slug: 'switch',
    title: 'Switch 开关',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['webkit 动画、禁用和 loading 状态需要持续视觉回归。'],
  },
  {
    slug: 'keyboard',
    title: 'Keyboard 虚拟键盘',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['fixed 底部浮层、毛玻璃与安全区需按 H5/App/小程序分别复核。'],
  },
  {
    slug: 'toast',
    title: 'Toast 轻提示',
    group: 'feedback',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['全局 manager、遮罩锁定和自动关闭时序需以交互断言验证。'],
  },
  {
    slug: 'upload',
    title: 'Upload 上传',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['文件选择、预览和 customRequest 依赖平台 API，需以交互断言补充截图验证。'],
  },
  {
    slug: 'verify-code',
    title: 'VerifyCode 验证码输入',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['聚焦、失焦、倒计时和输入法表现需按目标端持续回归。'],
  },
  {
    slug: 'timeline',
    title: 'Timeline 时间轴',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['水平时间轴、图片预览和 webkit 细节需要持续视觉回归。'],
  },
  {
    slug: 'textarea',
    title: 'Textarea 文本域',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['自适应高度、计数器、前后插槽和长文本换行需要持续回归。'],
  },
  {
    slug: 'time-picker',
    title: 'TimePicker 时间选择',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['格式化、清空、禁用和时间范围选择需要持续回归。'],
  },
  {
    slug: 'number-roller',
    title: 'NumberRoller 数字滚动',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['数字位数、千分位和小数滚动高度需要持续视觉回归。'],
  },
  {
    slug: 'overlay',
    title: 'Overlay 遮罩层',
    group: 'feedback',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['fixed 遮罩、锁滚动和点击穿透需按 H5/App/小程序分别复核。'],
  },
  {
    slug: 'picker',
    title: 'Picker 选择器',
    group: 'form',
    verifyStatus: 'verified',
    riskLevel: 'high',
    visualEnabled: true,
    riskNotes: ['⚠️可能存在平台差异：各端选择器 UI 与交互能力不同。'],
  },
  {
    slug: 'popup',
    title: 'Popup 弹出层',
    group: 'feedback',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['fixed 浮层、拖拽吸附、锁滚动与安全区需按目标端复核。'],
  },
  {
    slug: 'fab',
    title: 'Fab 悬浮按钮',
    group: 'feedback',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: false,
    riskNotes: ['拖拽吸边、毛玻璃与安全区定位需要交互回归，截图只作辅助。'],
  },
  {
    slug: 'tabs',
    title: 'Tabs 标签页',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['滚动与下划线动画在低端机型可能出现抖动。'],
  },
  {
    slug: 'tabbar',
    title: 'Tabbar 底部导航',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['fixed 底部定位、毛玻璃和安全区需按 App/H5/小程序分别复核。'],
  },
  {
    slug: 'tabbar-container',
    title: 'TabbarContainer 容器',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'high',
    visualEnabled: false,
    riskNotes: ['动态组件在小程序需插槽降级，fixed/filter/webkit 风险仍需平台回归。'],
  },
  {
    slug: 'sticky',
    title: 'Sticky 粘性布局',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['吸顶计算依赖节点尺寸与滚动位置，需校验自定义导航栏偏移。'],
  },
  {
    slug: 'tooltip',
    title: 'Tooltip 文字提示',
    group: 'feedback',
    verifyStatus: 'verified',
    riskLevel: 'high',
    visualEnabled: true,
    riskNotes: ['⚠️可能存在平台差异：定位与层级在 App/WebView 需重点验证。'],
  },
  {
    slug: 'waterfall',
    title: 'Waterfall 瀑布流',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'high',
    visualEnabled: true,
    riskNotes: ['⚠️可能存在平台差异：图片加载节奏会影响列高计算。'],
  },
  {
    slug: 'virtual-list',
    title: 'VirtualList 虚拟列表',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['长列表 transform 合成层与滚动事件节流需按目标端复核。'],
  },
  {
    slug: 'watermark',
    title: 'Watermark 水印',
    group: 'advanced',
    verifyStatus: 'verified',
    riskLevel: 'medium',
    visualEnabled: true,
    riskNotes: ['fullPage fixed 低层级水印需确认不遮挡导航、弹层和点击区域。'],
  },
  {
    slug: 'meta-row',
    title: 'MetaRow 结构行',
    group: 'basic',
    verifyStatus: 'verified',
    riskLevel: 'low',
    visualEnabled: true,
    riskNotes: ['用于信息行布局，建议重点验证长文本省略与金额对齐。'],
  },
];
