
/* prettier-ignore */
// @ts-nocheck
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LkButton: typeof import('./components/lk-button/lk-button.vue')['default']
    LkIcon: typeof import('./components/lk-icon/lk-icon.vue')['default']
    LkForm: typeof import('./components/lk-form/lk-form.vue')['default']
    LkFormItem: typeof import('./components/lk-form/lk-form-item.vue')['default']
    LkInput: typeof import('./components/lk-input/lk-input.vue')['default']
    LkTextarea: typeof import('./components/lk-textarea/lk-textarea.vue')['default']
    LkSwitch: typeof import('./components/lk-switch/lk-switch.vue')['default']
    LkCheckbox: typeof import('./components/lk-checkbox/lk-checkbox.vue')['default']
    LkCheckboxGroup: typeof import('./components/lk-checkbox/lk-checkbox-group.vue')['default']
    LkRadio: typeof import('./components/lk-radio/lk-radio.vue')['default']
    LkRadioGroup: typeof import('./components/lk-radio/lk-radio-group.vue')['default']
    LkTag: typeof import('./components/lk-tag/lk-tag.vue')['default']
    LkChoice: typeof import('./components/lk-choice/lk-choice.vue')['default']
    LkBadge: typeof import('./components/lk-badge/lk-badge.vue')['default']
    LkAvatar: typeof import('./components/lk-avatar/lk-avatar.vue')['default']
    LkLoading: typeof import('./components/lk-loading/lk-loading.vue')['default']
    LkProgress: typeof import('./components/lk-progress/lk-progress.vue')['default']
    LkTabs: typeof import('./components/lk-tabs/lk-tabs.vue')['default']
    LkTabPane: typeof import('./components/lk-tabs/lk-tab-pane.vue')['default']
    LkOverlay: typeof import('./components/lk-overlay/lk-overlay.vue')['default']
    LkModal: typeof import('./components/lk-modal/lk-modal.vue')['default']
    LkStepper: typeof import('./components/lk-stepper/lk-stepper.vue')['default']
    LkSlider: typeof import('./components/lk-slider/lk-slider.vue')['default']
    LkRate: typeof import('./components/lk-rate/lk-rate.vue')['default']
    LkPopup: typeof import('./components/lk-popup/lk-popup.vue')['default']
    LkToast: typeof import('./components/lk-toast/lk-toast.vue')['default']
    LkToastManager: typeof import('./components/lk-toast/lk-toast-manager.vue')['default']
    LkActionSheet: typeof import('./components/lk-action-sheet/lk-action-sheet.vue')['default']
    LkSkeleton: typeof import('./components/lk-skeleton/lk-skeleton.vue')['default']
    LkImage: typeof import('./components/lk-image/lk-image.vue')['default']
    LkCard: typeof import('./components/lk-card/lk-card.vue')['default']
    LkCell: typeof import('./components/lk-cell/lk-cell.vue')['default']
    LkCellGroup: typeof import('./components/lk-cell/lk-cell-group.vue')['default']
    LkNavbar: typeof import('./components/lk-navbar/lk-navbar.vue')['default']
    LkTabbar: typeof import('./components/lk-tabbar/lk-tabbar.vue')['default']
    LkTabbarItem: typeof import('./components/lk-tabbar/lk-tabbar-item.vue')['default']
    LkTabbarContainer: typeof import('./components/lk-tabbar-container/lk-tabbar-container.vue')['default']
    LkCollapse: typeof import('./components/lk-collapse/lk-collapse.vue')['default']
    LkCollapseItem: typeof import('./components/lk-collapse/lk-collapse-item.vue')['default']
    DemoBlock: typeof import('./components/demo-block/demo-block.vue')['default']
    LkTooltip: typeof import('./components/lk-tooltip/lk-tooltip.vue')['default']
    LkDropdown: typeof import('./components/lk-dropdown/lk-dropdown.vue')['default']
    LkDropdownItem: typeof import('./components/lk-dropdown/lk-dropdown-item.vue')['default']
    LkNoticeBar: typeof import('./components/lk-notice-bar/lk-notice-bar.vue')['default']
    LkSteps: typeof import('./components/lk-steps/lk-steps.vue')['default']
    LkStep: typeof import('./components/lk-steps/lk-step.vue')['default']
    LkTimeline: typeof import('./components/lk-timeline/lk-timeline.vue')['default']
    LkTimelineItem: typeof import('./components/lk-timeline/lk-timeline-item.vue')['default']
    LkDivider: typeof import('./components/lk-divider/lk-divider.vue')['default']
    LkSegmented: typeof import('./components/lk-segmented/lk-segmented.vue')['default']
    LkCalendar: typeof import('./components/lk-calendar/lk-calendar.vue')['default']
    LkDatePicker: typeof import('./components/lk-date-picker/lk-date-picker.vue')['default']
    LkTimePicker: typeof import('./components/lk-time-picker/lk-time-picker.vue')['default']
    LkUpload: typeof import('./components/lk-upload/lk-upload.vue')['default']
    LkVirtualList: typeof import('./components/lk-virtual-list/lk-virtual-list.vue')['default']
    LkWaterfall: typeof import('./components/lk-waterfall/lk-waterfall.vue')['default']
    LkCarousel: typeof import('./components/lk-carousel/lk-carousel.vue')['default']
    LkCarouselItem: typeof import('./components/lk-carousel/lk-carousel-item.vue')['default']
    LkBacktop: typeof import('./components/lk-backtop/lk-backtop.vue')['default']
    LkChartBar: typeof import('./components/lk-chart-bar/lk-chart-bar.vue')['default']
    LkChartLine: typeof import('./components/lk-chart-line/lk-chart-line.vue')['default']
    LkChartPie: typeof import('./components/lk-chart-pie/lk-chart-pie.vue')['default']
    LkGrid: typeof import('./components/lk-grid/lk-grid.vue')['default']
    LkSticky: typeof import('./components/lk-sticky/lk-sticky.vue')['default']
    LkPicker: typeof import('./components/lk-picker/lk-picker.vue')['default']
    LkSpace: typeof import('./components/lk-space/lk-space.vue')['default']
    LkIndexBar: typeof import('./components/lk-index-bar/lk-index-bar.vue')['default']
    LkIndexAnchor: typeof import('./components/lk-index-bar/lk-index-anchor.vue')['default']
    LkAnchor: typeof import('./components/lk-anchor/lk-anchor.vue')['default']
    LkAnchorLink: typeof import('./components/lk-anchor/lk-anchor-link.vue')['default']
    LkNumberKeyboard: typeof import('./components/lk-number-keyboard/lk-number-keyboard.vue')['default']
    LkKeyboard: typeof import('./components/lk-keyboard/lk-keyboard.vue')['default']
    LkVerifyCode: typeof import('./components/lk-verify-code/lk-verify-code.vue')['default']
    LkNumberRoller: typeof import('./components/lk-number-roller/lk-number-roller.vue')['default']
    LkCurtain: typeof import('./components/lk-curtain/lk-curtain.vue')['default']
    LkHorizontalScroll: typeof import('./components/lk-horizontal-scroll/lk-horizontal-scroll.vue')['default']
    LkFab: typeof import('./components/lk-fab/lk-fab.vue')['default']
    LkPreloadDebugger: typeof import('./components/lk-preload-debugger/lk-preload-debugger.vue')['default']
  }
}

export {}
